<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_AbstractHttpResponseCodec</name>
   <tag></tag>
   <elementGuidId>d95cec12-d3f9-40de-a994-4528ac725df6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'AbstractHttpResponseCodec')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>71c0f310-a2a7-45b6-8ade-5760e433e770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>org/openqa/selenium/remote/codec/AbstractHttpResponseCodec.html</value>
      <webElementGuid>fc7df15b-3f56-4f06-8a1c-54d58f873d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>class in org.openqa.selenium.remote.codec</value>
      <webElementGuid>bef95309-098e-41ea-bdf9-b99f3b686104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>classFrame</value>
      <webElementGuid>1d0c135c-8f95-468b-affc-40ae827cc4d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AbstractHttpResponseCodec</value>
      <webElementGuid>d2af84c9-548b-4d27-a5f8-542bdf328f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[@class=&quot;indexContainer&quot;]/ul[1]/li[6]/a[1]</value>
      <webElementGuid>ee7605f7-f008-434c-a908-0e01936f6579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_AddHasCasting/iframe_packageFrame</value>
      <webElementGuid>876dc06c-2900-4fbd-9fdc-ea84f65a021b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'AbstractHttpResponseCodec')]</value>
      <webElementGuid>7f37290c-d5fd-4a53-9ec3-3f33e67966d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AbstractHttpCommandCodec.CommandSpec'])[1]/following::a[1]</value>
      <webElementGuid>5f95723e-4bb8-4107-9226-4eab93019ca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AbstractHttpCommandCodec'])[1]/following::a[2]</value>
      <webElementGuid>6610b3f4-a3b4-448d-b117-57dd53a893ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AbstractWebDriverEventListener'])[1]/preceding::a[1]</value>
      <webElementGuid>0c8dd29c-097b-42a0-990b-446d9fb025e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AcceptedW3CCapabilityKeys'])[1]/preceding::a[2]</value>
      <webElementGuid>7cb413a6-a88c-41a2-bc57-2da560080053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AbstractHttpResponseCodec']/parent::*</value>
      <webElementGuid>e58d098c-73e1-4efb-bab0-20105f90568b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'org/openqa/selenium/remote/codec/AbstractHttpResponseCodec.html')]</value>
      <webElementGuid>70a39512-c2b5-4815-8d60-0b0651883ccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>9133a70e-ffa0-4885-b4c1-6cf340c3ed30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'org/openqa/selenium/remote/codec/AbstractHttpResponseCodec.html' and @title = 'class in org.openqa.selenium.remote.codec' and (text() = 'AbstractHttpResponseCodec' or . = 'AbstractHttpResponseCodec')]</value>
      <webElementGuid>fb4b702d-12fb-4343-803a-fb25269dc60f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
