<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_packageFrame</name>
   <tag></tag>
   <elementGuidId>01ab49bc-7657-4a1b-85ff-9bdd8b79628c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;packageFrame&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='packageFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b5583f71-1675-462a-ba97-85a25def95b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>allclasses-frame.html</value>
      <webElementGuid>246a3345-676b-4e9a-8413-af24ef7dd32e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>packageFrame</value>
      <webElementGuid>1f571749-1401-496a-926a-2e2512631311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>All classes and interfaces (except non-static nested types)</value>
      <webElementGuid>74673f71-67cc-482f-bfc3-f20d9760219c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;mainContainer&quot;]/div[@class=&quot;leftContainer&quot;]/div[@class=&quot;leftBottom&quot;]/iframe[1]</value>
      <webElementGuid>6b1d5023-2a91-4b30-a7d6-02874d40fdaa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='packageFrame']</value>
      <webElementGuid>0982d91f-2587-459d-891a-a9d374ac72b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/iframe</value>
      <webElementGuid>26887e14-0af9-4d6c-a8e5-c26e4c82db69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'allclasses-frame.html' and @name = 'packageFrame' and @title = 'All classes and interfaces (except non-static nested types)']</value>
      <webElementGuid>56ccc346-8af3-4fb3-bb92-f440e68ae1f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
