<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_Buzz</name>
   <tag></tag>
   <elementGuidId>1f127dc2-ef89-4584-986a-2a80cda0ad8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu_buzz_viewBuzz > b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_buzz_viewBuzz']/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>5be009f3-c8cf-4778-bf1c-30f7852efb5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buzz</value>
      <webElementGuid>228acfd5-9924-45ec-9694-34c3d58aaa8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_buzz_viewBuzz&quot;)/b[1]</value>
      <webElementGuid>cc16c95d-4dfe-4d71-a244-db2792713ae1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='menu_buzz_viewBuzz']/b</value>
      <webElementGuid>933d31be-1519-4a27-a9dc-8d23039b6287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Access Records'])[1]/following::b[1]</value>
      <webElementGuid>d2cb3263-bd22-48f7-aebd-f7df5c0d99c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Candidate Records'])[1]/following::b[1]</value>
      <webElementGuid>7023e6ea-3f03-41dc-82f7-df3238393d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/preceding::b[1]</value>
      <webElementGuid>a0ab469e-4f45-4312-9eea-3b5e7798f913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick Launch'])[1]/preceding::b[1]</value>
      <webElementGuid>0aca8da2-5b5f-40d0-96ca-916e3e2de4fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buzz']/parent::*</value>
      <webElementGuid>7612bb75-41d5-4add-84e0-d3d9819d8793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]/a/b</value>
      <webElementGuid>ead88685-341c-40c9-9ae6-3d864466ce75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'Buzz' or . = 'Buzz')]</value>
      <webElementGuid>543bb7db-d23a-4ed3-87ff-25bf8b21e8e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
