<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_Maintenance</name>
   <tag></tag>
   <elementGuidId>73f28e62-69a9-46b5-a2d0-0ae521fcb9de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_maintenance_purgeEmployee']/b</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu_maintenance_purgeEmployee > b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>6d8790bd-1186-4c9c-a2f8-7ec946f5aef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Maintenance</value>
      <webElementGuid>ca8e0e34-926a-438f-9c48-b3bc9d60b11e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainMenuFirstLevelUnorderedList&quot;)/li[@class=&quot;main-menu-first-level-list-item&quot;]/a[@id=&quot;menu_maintenance_purgeEmployee&quot;]/b[1]</value>
      <webElementGuid>7d1337bf-3e2a-44d4-b0e4-ded1c5842ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>bda5ab73-3ed6-4ff2-b2c5-6af9319b6781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Maintenance</value>
      <webElementGuid>b123243c-49f1-4a5c-a985-90a4f00a6275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainMenuFirstLevelUnorderedList&quot;)/li[@class=&quot;main-menu-first-level-list-item&quot;]/a[@id=&quot;menu_maintenance_purgeEmployee&quot;]/b[1]</value>
      <webElementGuid>9478f980-bb47-4680-b22f-23f6b11f040d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='menu_maintenance_purgeEmployee']/b</value>
      <webElementGuid>1bdb2225-b8b0-43fb-8a7e-e2692a685083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Directory'])[1]/following::b[1]</value>
      <webElementGuid>0df33100-bf16-4204-84a0-747a5dde4a1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::b[2]</value>
      <webElementGuid>bc659f6c-59a2-4df0-a68d-46d5e6dcd9af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee Records'])[2]/preceding::b[1]</value>
      <webElementGuid>b30344be-b718-4dec-91f9-b548ac7cf381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Candidate Records'])[1]/preceding::b[1]</value>
      <webElementGuid>095eef62-acbf-43b3-bb7a-2af0c373e1de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Maintenance']/parent::*</value>
      <webElementGuid>dd78a729-c926-4d5f-a40c-d234954dadfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/a/b</value>
      <webElementGuid>ba881e97-4a1d-457f-91aa-c1063cab9e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'Maintenance' or . = 'Maintenance')]</value>
      <webElementGuid>1eba2ba5-9f2b-48cf-b5ad-8bd60d5ccd54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
