<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Employee Name_empsearchemployee_nameempName</name>
   <tag></tag>
   <elementGuidId>53f143fb-71f0-423e-a70e-ad2ee2f33aa2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='empsearch_employee_name_empName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#empsearch_employee_name_empName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b857eb62-263c-43e0-ae17-99ecff8b3290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d986c50a-50e7-48e6-8e6e-d02fbebb3cd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>empsearch[employee_name][empName]</value>
      <webElementGuid>60e6b68b-583e-41bb-9487-585784c5637d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>empsearch_employee_name_empName</value>
      <webElementGuid>5441b845-6c1a-4503-bf40-62f7db66e647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ac_input</value>
      <webElementGuid>411af5f6-d148-4b4f-b4b2-782f1625f41d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>66a93b1f-0416-4be4-845f-4c667beb6f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;empsearch_employee_name_empName&quot;)</value>
      <webElementGuid>5ed72ed7-84bd-46c1-b194-8d51cf32b2ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='empsearch_employee_name_empName']</value>
      <webElementGuid>758201ea-5fe4-44b1-b44d-963ef2a5b308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_form']/fieldset/ol/li/input</value>
      <webElementGuid>0a0b8f8b-f12b-47a2-a44b-f36f427ac8e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>482e4960-df22-4a81-a084-ae27647194c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'empsearch[employee_name][empName]' and @id = 'empsearch_employee_name_empName']</value>
      <webElementGuid>ae1efe47-6020-4d02-a4ca-611be34eb88e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
